### ISSUE TITLE
Add toggler element to show/hide functionality

### ISSUE THREAD

**Issue by tjjalava** [SizeMeCom/sizeme-react#106]
@nomasi:

**Controlled by:**
sizeme_options.uiOptions.toggler = { off | on }

Default is off.

**What it does?**
If the toggler is on, a new element is written before all other sizeme content

![image](https://user-images.githubusercontent.com/886267/49701744-d3486b80-fbf8-11e8-8ffe-e26d47376932.png)

That makes it easier to style and possibly move the toggler around.  However the retailer can do a custom toggler by hiding our default one, and making one themselves.  Then the retailer’s custom toggler has to yell something in javascript to get our sizeme-content visible again.  

If the toggler is on, normal sizeme-content is hidden by default. The toggling state is preserved in a cookie “sm_toggled_visible” with values true or false.  This cookie value is read when loading (if toggler is on) and toggler and sizeme-content visibility state is adjusted to the state defined by the cookie.  

**Text:**
Add one text line in “common”: “togglerText”: “Find my size”

**Comment by nomasi** [comment]
A small revision is needed for this.  The toggler shouldn't be written at all (or at least should be hidden) if there is no product info ("resolved"?).  Otherwise the toggler will write itself, but there's nothing to toggle.
