### ISSUE TITLE
Size guide error when sizes are uncontinous?

### ISSUE THREAD

**Issue by nomasi** [SizeMeCom/sizeme-react#118]
The size guide of a normal SizeMe product fails with the console error message: "TypeError: "n[e] is undefined" if the sizes are not next to each other.  Demo page:

https://www.sizemedemo.com/wordpress/product/t-shirt/

The size L is missing and the size guide doesn't work.  

Also:

https://makiaclothing.com/product/shamrock-hooded-sweatshirt/

Same problem when only one size is present.

**Comment by tjjalava** [comment]
In the first example the size-selector initially contains four sizes, S, M, L and XL, but some code removes the L. Unfortunately at that point sizeme-selector-code has already initialized with four values, and when size guide is opened, tries and fails to show info for the missing size.
Same case with the second one.  

I'll add an undefined-check to the render-function, that should fix it.
