### ISSUE TITLE
Add tooltip to save measurements input box

### ISSUE THREAD

**Issue by nomasi** [SizeMeCom/sizeme-react#120]
Add a tooltip to the save measurement input box.  Features:

- allow multiple lines in text (such as measurementTooltips)
- Privacy policy link should open new browser window with our privacy policy; ideally it should be clean window with nothing extra (no header or footer) along the lines of:

`<a href="https://sizeme.com/privacy_clean.html"
   onclick="window.open(this.href,'targetWindow',
                                   'toolbar=no,
                                    location=no,
                                    status=no,
                                    menubar=no,
                                    scrollbars=yes,
                                    resizable=yes,
                                    width=600,
                                    height=400');
 return false;">Privacy Policy</a>`

But I don't know the usability of that on mobile.

**Comment by nomasi** [comment]
![sm_new_save_tooltip](https://user-images.githubusercontent.com/6150822/53403910-373f2c80-39bd-11e9-9964-cbd046232612.png)

**Comment by nomasi** [comment]
@tjjalava I'll try to start some work on this during the week

**Comment by tjjalava** [comment]
> * Privacy policy link should open new browser window with our privacy policy; ideally it should be clean window with nothing extra (no header or footer) along the lines of:
> 
> But I don't know the usability of that on mobile.

I think in mobile it just opens a new tab in the browser. Opening new windows might also cause some popup-blocker issues, and TBH, those windows never look good on any browser. Maybe we should try some sort of a lightbox instead? Like the login-popup? We can control the size of it, so on mobile it could be the whole screen, and on desktop a smaller popup.

**Comment by nomasi** [comment]
Lightbox is a lot better if it's not a big hassle to set up.  I don't know who ever opens these Privacy Policy links anyway.
