### ISSUE TITLE
Warning msg when no size selector is present

### ISSUE THREAD

**Issue by nomasi** [SizeMeCom/sizeme-react#134]
![image](https://user-images.githubusercontent.com/6150822/60614772-46544200-9dd6-11e9-84ac-b20a3c3d1217.png)

There seems to be a warning created at SizeSelector.js:214:20 if the product page doesn't have any size selector present.  This is to be expected so this shouldn't happen in production releases?

**Comment by nomasi** [comment]
Furthermore, there is an error message (product page 908:51) that could be related to our code.  At least, it is not present when our plugin is deactivated.  

Active:
![image](https://user-images.githubusercontent.com/6150822/60615615-3c334300-9dd8-11e9-9e23-515a9e8b1309.png)

Deactivated:
![image](https://user-images.githubusercontent.com/6150822/60615659-52d99a00-9dd8-11e9-8447-7ad399688656.png)

**Comment by tjjalava** [comment]
Any live example of the latter problem? Can't reproduce on Makia's site, Sizeme doesn't seem to be active there anymore?

**Comment by nomasi** [comment]
I'm able to reproduce this on their staging site, but I guess the only way to test there is to make a release (4.0.0?) and see how it goes?

**Comment by nomasi** [comment]
Release 4.0.0 didn't fix this one, but this part of the code wasn't the fault anyways.  The error message in Firefox pointed to the wrong place, but Chrome was better.  This was a problem with a custom piece of code for WooCommerce that did a jQuery change event on sizeMeChange or something like that.  I'll fix it at the plugin level.

**Comment by tjjalava** [comment]
It did fix the warning message from the size selector though, did it? Since that's what I tried to fix. Didn't do anything for the error message, since I couldn't reproduce it anywhere ;)
