### ISSUE TITLE
Ulkoasukohennuksia

### ISSUE THREAD

**Issue by tjjalava** [SizeMeCom/sizeme-react#20]
@nomasi:
- [x]  borderia vähän?
- [x]  scrollbarit pois (c9a269b)
- [x]  alapalkki pois?
- [x] slider grid-taustan skaalaus FF:ssä

Overlap: hidden varmaan ainakin
Miten SizeMe-info näkyy vai näkyykö ollenkaan?

**Comment by tjjalava** [comment]
@nomasi 
äh, vaikka tyylinä olisi overflow:scroll, mäkin chrome piilottaa scrollbarin jos ei scrollaa. Sen pitäis varmaan olla overflow:auto, niin sitä ei näkyis muuten kuin tarpeen mukaan. 
Syynä tohon ylipäätään on se, että modalin korkeus on suhteellinen ja voi mennä liian pieneksi jos selaimen kokoa pienentää.  Jos modalille antaa staattisen korkeuden, tai minimikorkeuden, ongelmia tulee myös, koska modalin ollessa näkyvissä, koko sivua ei pysty scrollaamaan (oon disabloinut sen tahallani, koska se oli aika tyhmän näköistä/oloista) ja liian pienellä ikkunalla modalista jää osa näkymättä.

**Comment by nomasi** [comment]
Sliderin grid -tausta bugaa vähän Firefoxissa @ rwd theme
![image](https://cloud.githubusercontent.com/assets/6150822/26504230/5ba5744a-424c-11e7-8da0-2355473a4d01.png)

Mahdollinen korjaus: 
background-size: 100% 100%;
![image](https://cloud.githubusercontent.com/assets/6150822/26504254/7925f4f4-424c-11e7-8d16-c110f97f8169.png)

Nopealla testillä ok @ muutkin teemat & IE11, Chrome & FF
