### ISSUE TITLE
Detailed window doesn't work

### ISSUE THREAD

**Issue by nomasi** [SizeMeCom/sizeme-react#82]
Error message:

 TypeError: a is undefined

Demo page: 
https://www.sizemedemo.com/magento19/t-shirt.html
Visible for logged-in SizeMe users only(?)

**Comment by nomasi** [comment]
I don't know if it's been properly specified that how the detailed view window should work with the new UI, but let's start the discussion! :)   If there is no working version for it now, let's just use the size guide for these logged in users too.

**Comment by tjjalava** [comment]
Issue is fixed now, at least the modal opens now. Some problems with sizing bar's splash-texts still remain
